In [2]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [4]:
import numpy as np

In [6]:
arr1=np.array([1,2,3])
print(arr1)

[1 2 3]


In [10]:
arr2=np.array([[1,2,3],[4,5,6]])
print(arr2)

[[1 2 3]
 [4 5 6]]


In [12]:
zeros=np.zeros((2,3))
print(zeros)

[[0. 0. 0.]
 [0. 0. 0.]]


In [14]:
random_arr=np.random.random((2,2))
print(random_arr)

[[0.81441885 0.3320582 ]
 [0.77828986 0.56949345]]


In [19]:
identity=np.eye(3)
print(identity)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [23]:
range_arr=np.arange(0,10,2)
print(range_arr)

[0 2 4 6 8]


In [25]:
arr=np.array([[1,2,3],[4,5,6]])
print("Shape: ",arr.shape)
print("Size: ",arr.size)
print("Data Type: ",arr.dtype)
print("Number of dimensions:",arr.ndim)

Shape:  (2, 3)
Size:  6
Data Type:  int32
Number of dimensions: 2


In [32]:
arr[1,1]

5

In [34]:
arr[1,-1]

6

In [36]:
arr[:,1:3]

array([[2, 3],
       [5, 6]])

In [40]:
arr1=np.array([1,2,3])
arr2=np.array([7,2,4])
print(arr1+arr2)
print(arr1*arr2)

[8 4 7]
[ 7  4 12]


In [44]:
arr1=np.array([[1,2,3],[4,5,6],[12,2,9]])
arr2=np.array([[6,2,4],[5,7,8],[8,14,7]])
print(arr1*arr2)
mul=np.dot(arr1,arr2)
print(mul)

[[ 6  4 12]
 [20 35 48]
 [96 28 63]]
[[ 40  58  41]
 [ 97 127  98]
 [154 164 127]]


In [48]:
arr=np.array([1,2,3])
print(np.exp(arr))
print(np.sqrt(arr))
print(np.log(arr))
print(np.std(arr))
print(np.max(arr))
print(np.min(arr))

[ 2.71828183  7.3890561  20.08553692]
[1.         1.41421356 1.73205081]
[0.         0.69314718 1.09861229]
0.816496580927726
3
1


In [54]:
arr=np.array([1,2,3,4,5,6])
reshaped=arr.reshape(2,3)
print(reshaped)

[[1 2 3]
 [4 5 6]]


In [60]:
arr=np.array([1,2,3,4,5,6])
print(np.array_split(arr,3))

[array([1, 2]), array([3, 4]), array([5, 6])]


In [62]:
arr=np.array([1,2,3])
view=arr.view()
view[0]=10
print(arr)

[10  2  3]


In [64]:
copy=arr.copy()
copy[0]=100
print(arr)

[10  2  3]


In [66]:
arr=np.array([1,2,3])
np.save('array.npy',arr)

In [68]:
loaded_arr=np.load('array.npy')
print(loaded_arr)

[1 2 3]
